server:
  port: 8083

#database proprties
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databasename=springmicroservice;encrypt=true;trustServerCertificate=true
    username: spring_user
    password: Arun3012#
  config:
    import: configserver:http://localhost:9296

  #jpa  proprties
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}